/** Pentagon numbers
  *
  * Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
  *
  * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
  *
  * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
  *
  * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
  */
def P(n: Int) = n * (3 * n - 1) / 2; def P(n: Long) = n * (3 * n - 1) / 2; def P(n: BigInt) = n * (3 * n - 1) / 2
def isP(x: Int) = ((Math.sqrt(24L * x + 1)+1)/6.0).isValidInt
val pentagonals = Stream.tabulate(Int.MaxValue)(P).drop(1).takeWhile(_ > 0)
val pentagonalPairs = pentagonals.combinations(2)

val matches = pentagonalPairs filter {
  case j #:: k #:: Stream.Empty =>
//    println(s"$j $k")
    isP(j+k) && isP(k-j)
}

matches toList